version: '3.3'

services:

  mysql:
    image: mysql:5.7
    restart: always
    labels:
      - "traefik.enable=false"
    networks:
      - internal
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: examples
      MYSQL_PASSWORD: examples
      MYSQL_DATABASE: gpdb
    container_name: mysql

networks:
  internal:
