# Use root/example as user/password credentials
version: '3.5'

services:
  backend:
    image: registry.gitlab.com/trthong95/todo_app:latest
    container_name: todo-app-be
    networks:
      - traefik_network
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

networks:
  traefik_network:
    external: true
