version: "3.3"

services:
  traefik:
    image: traefik:v2.2
    container_name: "traefik"
    command:
    - "--api=true"
    - "--api.dashboard=true"
    - "--log.level=DEBUG"
    - "--providers.docker"
    - "--entrypoints.web.address=:80"
    - "--entrypoints.websecure.address=:443"
    - "--certificatesresolvers.le.acme.tlschallenge=true"
    - "--certificatesresolvers.le.acme.email=nanolove95@gmail.com"
    - "--certificatesresolvers.le.acme.storage=/cert/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/etc/ssl/certs/:/cert"
      - "/var/run/docker.sock:/var/run/docker.sock"
    labels:
      - "traefik.http.routers.traefik.rule=Host(`api.thongnt.com`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=nanolove95:$$apr1$$BhRiDaDt$$/Eb9rkCD2lcOZ125odz4K/"
      - "traefik.http.middlewares.test-redirectscheme.redirectscheme.scheme=https"
      - "traefik.http.middlewares.test-redirectscheme.redirectscheme.permanent=true"

    networks:
      - network

networks:
  network:
