version: "3.3"

services:
  traefik:
    image: traefik:v2.2
    container_name: "traefik"
    command:
    - --api.insecure=true
    - --providers.docker
    - --entrypoints.websecure.address=:443
    - --certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
    - --certificatesresolvers.le.acme.email=nanolove95@gmail.com
    - --certificatesresolvers.le.acme.storage=/acme.json
    - --certificatesresolvers.le.acme.tlschallenge=true
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "./traefikdata:/"
      - "/var/run/docker.sock:/var/run/docker.sock"
    labels:
      - "traefik.frontend.rule=Host:api.thongnt.space"
    networks:
      - network

networks:
  network:
