version: '3.3'

services:

  mysql:
    image: mysql:5.7
    restart: always
    labels:
      - "traefik.enable=false"
    networks:
      - database
    ports:
      - 6603:3306
    environment:
      MYSQL_ROOT_PASSWORD: examples
      MYSQL_PASSWORD: examples
      MYSQL_DATABASE: gpdb
    container_name: mysql

networks:
  database:
